#!/usr/bin/env bash
#
# Writes ansible/inventory.ini from the VM's current address. The address comes
# from DHCP, so it is discovered at run time rather than written by hand.
#
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

require_domain
is_running || die "the VM is not running, so it has no address. Run 'make start'."

ip="$(wait_for_ip 120)" || die "the VM reported no address"

cat > "$ANSIBLE_DIR/inventory.ini" <<INV
# Generated by scripts/inventory.sh. Edits are lost on the next run.
[sandbox]
$VM_NAME ansible_host=$ip

[sandbox:vars]
ansible_user=$SSH_USER
ansible_ssh_private_key_file=$SSH_PRIVATE_KEY
INV

log "inventory written for $ip"
